on:
  workflow_call:
    inputs:
      bun-version:
        description: "A Bun version spec to use and install. Examples: 1.2.3, ^1.2.0, latest, stable, lts"
        type: string
        required: false
      bun-version-file:
        description: "A path to file containing Bun version spec. Examples: .bun-version .bvmrc"
        type: string
        required: false
      runs-on:
        # https://github.com/orgs/community/discussions/26801
        description: 'Type of machine of job to run on. Needs to be quoted, because to support self-hosted labels and inputs does not support Array nor multiple types (default: "ubuntu-latest")'
        type: string
        default: '"ubuntu-latest"'
        required: false
    secrets:
      NODE_AUTH_TOKEN:
        description: "The token to use for authentication with the registry."
        required: true

# outputs: - no output available

jobs:
  publish:
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.1.2
        with:
          bun-version: ${{ inputs.bun-version }}
          bun-version-file: ${{ inputs.bun-version-file }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run compose script if exists
        run: bun run compose || true

      - name: Build TypeScript project
        run: bun run build

      - name: Publish/release package to npm and GitHub packages registry
        run: bun run release
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
